### ISSUE TITLE
[documentation?] Release parameter should be of specific format?

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry-php#688] opened 2018-11-12 16:21 UTC
We're trying to pass our release information into the Raven_client (v 1.9.2) in various ways but none of them seem to work:

1. we tried using the tag we use (i.e. `OUR_RELEASE_201811051788`) using the following code:
```php
$release = 'OUR_RELEASE_201811051788';
$client = new Raven_Client($sentryDSN);
$client->setRelease($release);
```
This failed

2. using the direct constructor way:
```php
$release = 'OUR_RELEASE_201811051788';
$client = new Raven_Client($sentryDSN, ['release' => $release]);
```
again this failed.

3. We thougt that Sentry might have issues with the naming of our tag... Thus we use the Git hash:
```php
$release = '4b22668 '; // mind the extra space there i know
$client = new Raven_Client($sentryDSN, ['release' => $release]);
```
Again this failed... 

4. I'm now trimming the git hash to make sure it's just a alphanumeric string... (`4b22668`)

~~I'm still waiting on the results from that last test..~~ **edit: this works... **

My question is... Is there some type of format limit for the release variable? Can it only be a git hash or can it also point to a tag on the repo ?

Thanks!

**Comment by untitaker** [comment] 2018-11-12 17:33
Correction: Releases are auto-created. @fruitl00p could it be you have something in the settings that filters out that release? What do you mean by "this failed"?

**Comment by fruitl00p** [comment] 2018-11-12 20:47
@Jean85 @untitaker 
Releases don't have to be preregistered in order for issues to be collected / organized into them. They do however need a specific (or better yet: only accept) a specific format. As i mentioned in the issue itself: when using only a 8 char git hash (`4b22668`) the release field is filled and it works. 

The only `real` issue now is that this information seems missing from the documentation (or at least I couldn't find it anywhere and now have to change my release schema from tags to git-hashes... )

**Comment by untitaker** [comment] 2018-11-12 21:13
This is not intentional behavior, so we need to get at the bottom of why only particular releases work for you. Again, please say what you mean by "failing" so I can try to reproduce it.

**Comment by untitaker** [comment] 2018-11-13 09:01
@fruitl00p I think your release has a newline after it. We can't reproduce this with a regular space.

I think the SDKs should strip whitespace there

**Comment by fruitl00p** [comment] 2018-11-13 09:03
@untitaker but what about the last example using the Git tag we have... (`KMT_RELEASE_201811 etc`) Is that also due to a possible newline... ? I didnt check that...

**Comment by untitaker** [comment] 2018-11-13 09:03
I mean I tried to repro all of them and I could only get it to fail with trailing newlines. Any other string works

**Comment by ste93cry** [comment] 2018-11-21 12:36
Issue has been resolved server-side (you can find better details in the linked issue) so I'm going to close this

**Comment by untitaker** [comment] 2018-11-21 12:39
@ste93cry the linked issue is for the python SDK.

**Comment by ste93cry** [comment] 2018-11-21 12:42
My bad I saw python code and thought it was of the Sentry's codebase. Reopening this then

>I believe that the SDKs should strip this value before sending it to the server.

It's an easy fix and costs nothing to do it but I believe instead that this should be done (also?) server-side for a few reasons:

- any SDK has to make the same change and maintain it: today the problem is in the `release` attribute and tomorrow it could be in something else
- the server should always sanitize and normalize the data (imho)

**Comment by untitaker** [comment] 2018-11-21 13:09
This wouldn't be my general approach to things as sentry's normalization code grew incredibly complex because of minor things like this. String stripping might be ok. I would fix this in the SDK for now, we're currently rewriting serverside normalization and generally want to be much stricter about things. The error messages will also be nicer.

**Comment by ste93cry** [comment] 2019-12-15 22:03
Closing as this issue is one year old and I believe that since the `release` is something controlled by the user then it's up to him to set a valid value

**Closed by ste93cry** 2019-12-15 22:03 UTC
Labels: Status: Won't fix, Type: Question
