### ISSUE TITLE
Array serialization truncation too aggressive

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-php#315] opened 2016-07-05 17:37 UTC
All arrays are currently being truncated to "Array of length N":

https://github.com/getsentry/sentry-php/blob/c8bc22e148bd7ad25bcb29d70182318c7b493b18/lib/Raven/ReprSerializer.php#L35

... and yet dictionaries are fully expanded. We are getting feedback from users with error data containing small arrays (e.g. 1-5 items) that are frustrated that they cannot see inside.

**Comment by lupoair** [comment] 2016-08-01 15:23
Yes, frustrating!

**Comment by dcramer** [comment] 2016-08-01 16:29
I'm closing this out as we expand arrays in PHP.

**Comment by idoberko2** [comment] 2017-08-21 07:38
This issue still exists. Will it be fixed?

**Comment by dcramer** [comment] 2017-08-21 15:54
Just ton confirm, where are these arrays not getting expanded? (which section of the event)

**Comment by idoberko2** [comment] 2017-08-22 05:52
Additional Data. For example, we receive JSON webhooks from 3rd parties and send events to sentry in case of failure. Attached an example of how one of these JSONs look in Sentry:
![image](https://user-images.githubusercontent.com/6158608/29550590-2d094f48-8717-11e7-8fe8-e00cda7114c0.png)

**Comment by Jean85** [comment] 2017-08-22 09:32
We should anyway limit the depth or let it be configurable, to avoid sending data too "deep".

**Comment by dcramer** [comment] 2017-08-22 20:35
I'm trying to recall why we went this direction in the first place. I think there were certain things where we didn't want the full data repr, but honestly dont recall where.

**Comment by rentalhost** [comment] 2017-08-25 11:53
In my case, this additional data are required to make possible fix my issue, once that the problem is inside of this truncated array.

**Comment by pontus-mp** [comment] 2017-11-13 08:15
According to support this feature is intended to help keep error messages within the 100kb payload limit. 

Maybe it would be possible to only flatten when the limit is hit, or make it opt-out? Those who are migrating from another solution (like us) are probably already having their error messages somewhat in check.

**Comment by Jean85** [comment] 2017-11-13 08:54
In the 1.8.1 release that just got out, we added setters for the serializers. You can replace them with the logic you prefer.

**Comment by gsouf** [comment] 2017-11-16 10:13
Hi @Jean85 can you give details about this method?

In my case the data truncated from ``$_SESSION`` are required to reproduce the error. To workarround the depth limit, I currently send a json encoded copy of ``$_SESSION`` (with pretty print) in ``extra`` param.

**Comment by Jean85** [comment] 2017-11-16 10:16
I'm referencing this piece of code: https://github.com/getsentry/sentry-php/blob/e1001f80d07f08cbf8d2648cb707ea43bf3e5794/lib/Raven/Client.php#L1457-L1471

Those 2 serializers are the classes responsible for the compression of those arrays. You can extend them and change the behavior for the desired stuff. But using the extra field like that is a feasible solution too!

**Comment by gsouf** [comment] 2017-11-16 10:42
Thanks @Jean85 
Unfortunately setting the serializer was not useful in my case because the depth is set in ``Client::sanitize`` and wanted to set a greater depth for user data only.

I end up be ovewritting sanitize method to do the job. Here is an example in case it can help anyone:

```php
class MyRavenClient extends \Raven_Client
{

    /**
     * @param array $data
     */
    public function sanitize(&$data)
    {
        // Serializes the session items as a json string
        foreach ($data['user']['data'] as $k => $v) {
            if (is_array($v)) {
                foreach ($v as $kk => $vv) {
                    $data['user']['data'][$k][$kk] = json_encode($vv, JSON_PRETTY_PRINT, 3);
                }
            }
        }


        // use parent sanitizer
        parent::sanitize($data);
    }

}
```
 Be aware that serializer will limit the size of a string, and in this case it might be useful to provide an other serializer that has a greater limit on string size.

**Comment by Wirone** [comment] 2018-10-19 13:20
Also having this:

![image](https://user-images.githubusercontent.com/600668/47220430-0f5a0f80-d3b2-11e8-8d14-c6ac813e707b.png)

This relates to issues created via overriden Monolog's `RavenHandler` in Yii2 app (don't ask....).

I'll probably normalize trace to flat array, but still, this is frustrating.

**Comment by philraj** [comment] 2019-05-16 12:03
Any movement on this?

**Comment by Jean85** [comment] 2019-05-16 14:01
Did you check out the new 2.0 release? The serializer has that option and it's completely replaceable if you want.

Also, there's #632 which just needs to be released.

**Comment by philraj** [comment] 2019-05-16 14:50
@Jean85 that's great news, thank you. Will definitely be trying that out.

**Comment by stayallive** [comment] 2019-09-19 21:47
This should be resolved in both 1.x and 2.x (but please use 2.x where possible).

Or well, the "culprit" is now configurable so if you run into this often it's possible to modify the settings for this behaviour.

1.x: #632
2.x: https://github.com/getsentry/sentry-php/issues/378#issuecomment-533318398

**Closed by stayallive** 2019-09-19 21:47 UTC
