### ISSUE TITLE
Potential Regression: Unexpected Data Truncation

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-php#281] opened 2016-05-06 15:37 UTC
Example from customer data:

```
{
  http_code: 422, 
    response: {
      errors: Array of length 1
    },
  url: https://blah.example.com/x
}
```

The errors array is removed instead of shown. This should be improved. (Independently of this, strings are not visible as strings because quotes are missing. Not sure if that was the same before)

**Comment by mitsuhiko** [comment] 2016-05-06 15:37
@dcramer i can have a look at this but i'm not sure if you have preferences of how to deal with this.

**Comment by dcramer** [comment] 2016-05-06 15:55
Was this data in extra or somewhere else? I want to confirm that the PR actually targets this.

**Comment by dcramer** [comment] 2016-05-08 15:57
I'm closing this out as fixed until more info is available

**Comment by DD-Jeroen** [comment] 2016-09-14 06:04
The data is in extra indeed:

![array of length n](https://cloud.githubusercontent.com/assets/16835361/18501565/bb26ba0a-7a51-11e6-8f8c-5791ec13e17a.png)

I still experience this issue with 1.2.0.

**Comment by dcramer** [comment] 2016-09-15 05:54
@DD-Jeroen I cannot reproduce this on 1.2.0 with the exact test case in your screenshot:

```
    public function testSanitizeExtra()
    {
        $client = new Dummy_Raven_Client();
        $data = array('extra' => array(
            'context' => array(
                'line' => 1216,
                'stack' => array(
                    1, array(2), 3
                ),
            ),
        ));
        $client->sanitize($data);

        $this->assertEquals($data, array('extra' => array(
            'context' => array(
                'line' => 1216,
                'stack' => array(
                    1, 'Array of length 1', 3
                ),
            ),
        )));
    }
```

I'm also having trouble explaining how else it could be happening

**Comment by DD-Jeroen** [comment] 2016-09-15 05:56
Thanks for trying. I'll try to create a test case myself later this week.

**Comment by dcramer** [comment] 2016-09-15 05:57
@DD-Jeroen going to also add a few more tests around this, and improve some of the behavior. Maybe I'll flush out the issue while doing this.

**Comment by DD-Jeroen** [comment] 2016-09-24 12:05
I found out that the transformation is performed in Raven_Serializer::serializeValue(). Does this help?

**Comment by stayallive** [comment] 2017-06-15 11:35
@DD-Jeroen is this still a problem in the latest version?

**Comment by Gerfaut** [comment] 2018-01-21 15:34
Hi, 

I came across the same problem with the last version. 
Isn't possible to change the serializeValue method to something like this?

    /**
     * @param mixed $value
     * @return string|bool|double|int|null
     */
    protected function serializeValue($value)
    {
        if (is_null($value) || is_bool($value) || is_float($value) || is_integer($value)) {
            return $value;
        } elseif (is_object($value) || gettype($value) == 'object') {
            return 'Object '.get_class($value);
        } elseif (is_resource($value)) {
            return 'Resource '.get_resource_type($value);
        } elseif (is_array($value)) {
            return json_encode($value); //<--- Dump the array to see at least something
            //return 'Array of length ' . count($value); <--- Previous implementation
        } else {
            return $this->serializeString($value);
        }
    }

Thanks a lot, 

_Gerfaut_

**Comment by Jean85** [comment] 2018-01-22 08:27
@Gerfaut the issue is that we have an hard limit to the dimension of the data sent to Sentry. I agree that that implementation may be suboptimal, but we are working on it in the 2.x branch (see #534)

**Comment by Gerfaut** [comment] 2018-01-25 22:12
Hi @Jean85, 

Indeed, I can understand! Thanks for the info, I'll follow the other thread. 
Thanks a lot!

**Comment by stayallive** [comment] 2019-09-19 21:39
I believe a solution was requested in #378 which has been resolved in 2.x.

> https://github.com/getsentry/sentry-php/issues/378#issuecomment-533318398

**Closed by stayallive** 2019-09-19 21:39 UTC
