### ISSUE TITLE
monolog/monolog ^2 is outdated

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/sentry-php#1319] opened 2022-05-19 11:54 UTC
### Problem Statement

Please update `monolog/monolog` dependency to ^3.0

**Comment by Jean85** [comment] 2022-05-19 13:28
Sorry but we can't simply update it, we would cut off anyone that is stuck on "older" versions.

Also, closing this as duplicate of #1318

**Closed by Jean85** 2022-05-19 13:28 UTC
Labels: Status: Won't fix
