### ISSUE TITLE
Can Sentry send notices and warnings at user defined moments?

### ISSUE THREAD

**Issue by sgabler** [getsentry/sentry-php#854] opened 2019-07-19 10:47 UTC
We inherited a legacy system where we integrated Sentry (it's been very helpful!). Unfortunately that legacy system is not built very elegantly, so we are in the following situation (simplified):

- we have an endless loop that consumes jobs
- these jobs can cause warnings and notices that we would like to be informed of in Sentry
- currently those warnings and notices are only sent once the php process shuts down
- unfortunately the system regularly runs `pkill php` (don't ask 😉), which seems to prevent sentry from sending those accumulated warnings and notices

Is there any way to send those warnings and notices synchronously? Let's say at the beginning or end of each loop iteration?

Pseudo code:

```php
while (true) {
    sendAccumulatedSentryWarningsAndNotices();
    processJob();
}
```

We investigated, but it seems that this is not a use case that is currently supported. We would appreciate any ideas or input here. Thank you

**Comment by ste93cry** [comment] 2019-08-21 12:43
Closing this as it's a duplicate of an already existing issue

**Closed by ste93cry** 2019-08-21 12:43 UTC
