### ISSUE TITLE
Warning: exec(): Unable to fork [curl -X ...

### ISSUE THREAD

**Issue by hason** [getsentry/sentry-php#330] opened 2016-08-01 13:23 UTC
- curl_method: exec
- possibly related to #284 ?

**Comment by ste93cry** [comment] 2017-06-15 22:29
There are not enough information to understand the cause of the issue. If you think it was related to #284, and given that that issue has been marked as fixed I'm going to close this too. Feel free to reopen it if you still get the error

**Closed by ste93cry** 2017-06-15 22:29 UTC
