### ISSUE TITLE
How do I set error levels? Ie. Ignore INFO-level.

### ISSUE THREAD

**Issue by otang** [getsentry/sentry-php#521] opened 2017-12-06 01:24 UTC
I was unable to find this in the docs. Thank you.

**Comment by Jean85** [comment] 2017-12-06 08:30
You have to set the `error_types` option of the client. It has the same functionality of the `error_reporting` PHP constants: http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

**Comment by otang** [comment] 2017-12-07 02:13
@Jean85 Thank you for the reply. I am setting error levels, please see screenshot:
![image](https://user-images.githubusercontent.com/800081/33695245-19b6e23c-dab1-11e7-88a7-efb4478c097b.png)

However I'm still getting errors submitted for INFO levels.

**Comment by stayallive** [comment] 2017-12-07 09:03
@otang on what PHP version are you and can you past the actuall error message you are seeing in Sentry. My assumption is that PHP 7+ might submit those info's as an Exception instead of Error (because some are now Catchable as Exceptions).

**Comment by otang** [comment] 2017-12-07 21:55
@stayallive We're using PHP 5.5.3. There is no error message, it's just that I'm unable to prevent sentry from sending log level INFO.

**Comment by otang** [comment] 2017-12-19 06:28
@stayallive We're using PHP 5.5.3

**Comment by stayallive** [comment] 2017-12-21 09:56
@otang Using this code I am not being able to reproduce the issue.

```php
<?php
require_once __DIR__ . '/lib/Raven/Autoloader.php';
Raven_Autoloader::register();

$client = new Raven_Client('http://public:secret@example.com/1', array('environment' => 'test'));

$handler = new Raven_ErrorHandler($client);
$handler->registerExceptionHandler();
//$handler->registerErrorHandler(); // If this register is used the event id is filled
$handler->registerErrorHandler(true, (E_ERROR | E_PARSE)); // When this one is active no event is being submitted
$handler->registerShutdownFunction();

trigger_error('This is an info message!', E_USER_NOTICE); // Which translates to INFO

var_export($client->getLastEventID());
```

Can you show me the actual error that is being reported to Sentry?

Also if your are submitting an message or something yourself to Sentry (using the $client) the error types won't have effect. The error handler only deals with PHP generated errors / exceptions.

**Comment by stayallive** [comment] 2018-04-20 15:56
Closing this issue because it is quite old, if there is still a problem please open a new issue.

**Closed by stayallive** 2018-04-20 15:56 UTC
Labels: support
