### ISSUE TITLE
HubAdapter::captureMessage deprecation in symfony

### ISSUE THREAD

**Issue by pkly** [getsentry/sentry-php#1211] opened 2021-04-17 09:51 UTC
Hello,

The interface `Sentry\State\HubInterface` contains an optional argument for `EventHint|null $hint` which in turn causes deprecation errors because `Sentry\State\HubAdapter` does not implement it when the sentry-symfony package in an application.
If possible could you add the missing parameters to the interfaces and classes which implement it? The only downside is that some people might have to define an additional argument to their classes which implement it if they haven't already.

This happens with the following:
Symfony 4.4.x (lts) dev+debug enabled
sentry/sentry 3.2.1
sentry/sentry-symfony 4.0.3

**Comment by ste93cry** [comment] 2021-04-17 10:05
Duplicate of #1206

**Closed by ste93cry** 2021-04-17 10:05 UTC
Labels: Status: Confirmed, Type: Bug
