### ISSUE TITLE
JSON encoding data with invalid unicode characters fails

### ISSUE THREAD

**Issue by tacovandenbroek** [getsentry/sentry-php#875] opened 2019-08-30 12:55 UTC
https://github.com/getsentry/sentry-php/blob/646f6ada8b89a08063e31f54ed6d260bd6879239/src/Util/JSON.php#L27

When the event that is being captured contains invalid utf-8 characters (e.g. in the request data and/or the stack trace), the `json_encode` call will fail. This results in a fatal error about json encoding being captured instead of the underlying issue. As of PHP 7.2 these characters can be ignored using either the `JSON_INVALID_UTF8_IGNORE` or `JSON_INVALID_UTF8_SUBSTITUTE` flag in `json_encode`. Maybe one of these flags could be used if they are available?

**Comment by ste93cry** [comment] 2019-08-30 13:28
Closing as duplicate of #828

**Closed by ste93cry** 2019-08-30 13:28 UTC
