### ISSUE TITLE
Do not call magic methods when seralizing object IDs in stack traces

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-php#1476] opened 2023-02-24 10:47 UTC
This also invokes magic `__isset()` (and then `__get()` ) method for objects, which can be problematic if these magic methods have side effects. Which is exactly what I had to investigate and deal with in our own codebase today.

I'd propose that this behavior (magically getting some kind of ID of objects present within traceback) should check if the property _actually_ exists first _(via `property_exists()`, which doesn't invoke magic methods)_.

Or at least this magic feature should be optional - i,e. there should be an option to disable it.

_Originally posted by @smuuf in https://github.com/getsentry/sentry-php/pull/1443#discussion_r1116010136_

**Comment by smuuf** [comment] 2023-02-24 11:44
Thanks you for creating the issue as I haven't had the time to do it myself yet.

**Comment by stayallive** [comment] 2023-02-27 12:02
@smuuf I am curious about your usecase here. I would not expect a `__isset` and `__get` to have any side effects since they are existence checks and a getter (which in theory should never have side-effects), what is your use-case where they do have side-effects?

I did propose a fix in #1483, but I am still not sure if it's really needed... so curious about your case!

**Comment by smuuf** [comment] 2023-02-28 10:30
@stayallive As you say - _"in theory"_ 😄 As no one can enforce that the magic `__isset/__get` will not have side effects, one has to presume that they might have.

Our specific case was (I admit) a rather convoluted one, but nevertheless it's what was happening.

1. https://www.notorm.com/#api (https://www.notorm.com/) - uses `__isset/__get` to represent/access relationships among tables/rows.
    - For example like this:
        - ![obrazek](https://user-images.githubusercontent.com/6860713/221816198-bc6f07c4-af3c-4638-9c2a-32060509d24b.png)
2. Some debugging libraries - in our case https://github.com/nette/tracy (https://tracy.nette.org/cs/) - register their own exception & error handler. - which ***may*** be registered in such order _(in relation to Sentry's own handlers)_ that the Tracy's handlers are invoked first. Also, some debugging libraries may have something which Tracy calls "strict mode" - they handle errors/exceptions that are triggered - display them and then they totally `die()`.
4. Then, some exception happens in our code _(in our case it was some `TypeError`)_ - and one of the arguments present in the traceback is our `NotORM` object representing some DB row.
5. Sentry tries to serialize the traceback's arguments - stumbles upon our `NotORM` object _(representing some DB row)_ and tries to access `$object->id` _(which really is `$databaseRow->id`)_, which then fails with `Undefined array key "id_id"`, because accessing `$row->id` expects to find a defined relationship between that row's own table and another table called `id`.
    - ![obrazek](https://user-images.githubusercontent.com/6860713/221822986-3814be5e-3b26-48d5-ba86-76576eed5cc6.png)
6. A warning is emitted, _(apparently)_ Sentry's error handler converts it into exception _(here I'm not sure exactly about the correct order of things)_, which Tracy catches, displays it and then stops the execution.

_... or something like that ..._

In any case, ***what we got as error message was a warning*** originating from the fact that Sentry was trying to access magic `id` property on some traceback's argument - and ***not the `TypeError` which was the original bug in our code*** - and we had no way of knowing this.

After I spent some time investigating this, I compacted my argument to _"Accessing `$obj->id` may have unexpected side effects"_. Even though our case was a bit convoluted _(I'm not even really sure now if I traced the problem and its partial steps correctly)_, the problem can really be boiled down to this:

> Magic issetters/getters ***can*** have side effects and the only really safe solution is to check if the `id` property really exists and one is 100% sure that accessing it does not do anything else.

**Comment by smuuf** [comment] 2023-02-28 10:44
And here is what I came up with when trying to create a minimum-reproducible-example (even without Tracy):

```php
<?php

//
// Needs:
// composer require sentry/sentry==3.13.1 php-http/curl-client guzzlehttp/psr7 php-http/message 
//

require __DIR__ . "/vendor/autoload.php";

ini_set('zend.exception_ignore_args', '0');
ini_set('display_errors', 1);

set_error_handler(function(...$args) {
	$str = json_encode($args);
	echo "Caught error and exiting! Info: $str";
	die;
});

\Sentry\init([
	'dsn' => 'https://aaaaabbbbbcccccdddddeeeeefffff12@localhost/0',
]);

error_reporting(E_ALL);

function _reproduce_sentry_stuff() {

	$someObj = new class {
		private $emptyArray = [];

		public function __isset($name) {
			$this->emptyArray[$name];
		}
	};

	_throw_exception($someObj);

}

function _throw_exception($obj) {
	throw new ErrorException("Some exception I want to know about");
}

echo "reproducing\n";
_reproduce_sentry_stuff();
```

Then, what I got:
```
$ php sentry_stuff.php
reproducing
Caught error and exiting! Info: [2,"Undefined array key \"id\"","\/mnt\/w\/php\/_bugs\/sentrystuff.php",31,[]]
```

... and what I wanted:

```
$ php sentry_stuff.php
reproducing
PHP Fatal error:  Uncaught ErrorException: Some exception I want to know about in /mnt/w/php/_bugs/sentrystuff.php:40
```

**Comment by cleptric** [comment] 2023-02-28 10:46
Thanks a lot for the great write-up!
Does https://github.com/getsentry/sentry-php/pull/1483 fix your issue?

**Comment by stayallive** [comment] 2023-02-28 11:06
That is awesome, and thanks for the incredibly detailed response, it actually kinda makes sense what you are seeing. I was a little on the fence about the fix but reading this I'm happy we are making it, closing the issue since we got it merged and fixed but the actual release might take a few days. Thanks for reporting and detailing 👍

**Closed by stayallive** 2023-02-28 11:06 UTC
Labels: Type: Bug, Status: In Progress

**Comment by cleptric** [comment] 2023-03-06 08:42
Released via https://github.com/getsentry/sentry-php/releases/tag/3.14.0
