### ISSUE TITLE
Checking for @ in handleError

### ISSUE THREAD

**Issue by bm-pzegardlo** [getsentry/sentry-php#332] opened 2016-08-08 07:58 UTC
If PHP expression was prefixed by @ and error occured, error_reporting() will return 0 in registered error handler. This error will not be logged in Sentry cause in handleError there is a checking that error_reporting is not equal to 0.

The same will happen if error_reporting would be set to 0 in a global scope, so checking for this in a handleError and handleFatalError function is imho not a good idea. In my opinion handle error function should looks like this:

```php
       public function handleError($code, $message, $file = '', $line = 0, $context=array())
       {
            $error_types = $this->error_types;
            if ($error_types === null) {
                $error_types = error_reporting();
            }
            if ($error_types & $code) {
                $e = new ErrorException($message, 0, $code, $file, $line);
                $this->handleException($e, true, $context);
            }
            if ($this->call_existing_error_handler) {
                if ($this->old_error_handler !== null) {
                    return call_user_func($this->old_error_handler, $code, $message, $file, $line, $context);
                } else {
                    return false;
                }
            }
       }
```

**Comment by dcramer** [comment] 2016-08-08 17:49
This is definitely a concern. Realistically I dont think Sentry should *ever* capture errors when they're suppressed, but I couldn't come up with a clean way to do that. If we say "if error_reporting() is 0, dont capture it", that might be ok. My only concern would be when people disable error reporting, and I'm not sure how common that is.

**Comment by dcramer** [comment] 2016-08-11 19:08
So I guess we have to pick our poison here.

We can:

- Never log errors if error_reporting(0) is set
- Log errors that are suppressed, unless you filter them out via error_types

**Comment by davejamesmiller** [comment] 2016-08-11 19:16
I think the former would be better - don't log them.

There are definitely legitimate reasons for using the @ suppressor, and we don't want all of those errors logged in Sentry, but also don't want to disable an entire class of error just for those few cases. However in the other case I can't think of any good reason to set error_reporting to 0 globally - even on a production system you'd want it set to E_ALL (or similar) and just turn display_errors off.

My only concern would be if the user accidentally had error_reporting set to 0 and never realised... One possibility would be to check the error_reporting level when the registerErrorHandler() function is called, and either throw an exception immediately (fail fast so they can fix it) or quietly switch back to using error_types only (harder to debug but won't break a production system).

**Comment by bm-pzegardlo** [comment] 2016-08-11 19:44
What about adding the configuration option to control this? If someone will want to log suppressed errors will be could.

**Comment by dcramer** [comment] 2016-08-11 19:47
@bm-pzegardlo I'd be open to it, but IMO its fairly complex and makes it easy to shoot yourself in the foot.

**Comment by dcramer** [comment] 2016-08-11 19:48
Going to close this out as we're going to document how to capture them, but open to PRs to improve this as long as they dont icnrease complexity greatly

**Comment by bm-pzegardlo** [comment] 2016-08-11 19:50
thx, i'm gonna to make the PR for this :)

**Comment by SeBsZ** [comment] 2016-09-15 14:22
Any updates on this ticket? I apologize for my message, but I am wondering if there is still a bug regarding handling of suppressed errors in Sentry.

I'm using this code to initialize Sentry:
`Raven_Autoloader::register();
  $sentry_client = new Raven_Client(SENTRY_DSN);
  $error_handler = new Raven_ErrorHandler($sentry_client);
  $error_handler->registerExceptionHandler();
  $error_handler->registerErrorHandler(true, E_ALL);
  $error_handler->registerShutdownFunction();`

According to lib/client.php this is version 1.2.0. We're using E_ALL because want to capture all kinds of errors, notices, messages etc. but NOT suppressed errors. The problem is Sentry is showing all the suppressed errors as well:

http://i.imgur.com/vxrQKsa.png

According to these docs suppressed errors should never be reported - https://docs.sentry.io/hosted/clients/php/usage/#error-control-operators. Your messages above got me confused though, as they also indicate suppressed errors should never be reported. Is this a bug or am I doing something wrong?

Thanks a lot.

**Comment by dcramer** [comment] 2016-09-15 19:32
@SeBsZ the biggest issue is we haven't identified any actual issues via tests. If we could reproduce this I'm certain we could resolve it. Would you mind taking a stab at reproducing it in an isolated environment (with as minimal code as possible)?

**Comment by SeBsZ** [comment] 2016-09-15 21:08
Sure. Just gave this a quick try. Here's the full PHP test file I came up with:

'<?php'
'if (file_exists(__DIR__ . '/../vendor/sentry/sentry/lib/Raven/Autoloader.php')) {'
'    require_once __DIR__ . '/../vendor/sentry/sentry/lib/Raven/Autoloader.php';'
'}'

'define('SENTRY_DSN','https://snipsnip@app.getsentry.com/65762');'

'//Initialize Sentry'
'Raven_Autoloader::register();'
'$sentry_client = new Raven_Client(SENTRY_DSN);'
'$error_handler = new Raven_ErrorHandler($sentry_client);'
'$error_handler->registerExceptionHandler();'
'$error_handler->registerErrorHandler(true, E_ALL);'
'$error_handler->registerShutdownFunction();'

'//Produce an error'
'$my_array = array();'

'//This line shouldn't produce a notice'
'$result = @$my_array[2];'

'//This line should produce a notice'
'//$result = $my_array[2];'

'echo "Result: ".$result;'
'?>'

As soon as I run that file, I'm greeted by the notice in Sentry, whereas it should have been suppressed:

http://i.imgur.com/P99LMtx.png

Let me know if I can debug Sentry - I'm set up with a full PHP debugger so I can step through code. I just don't know which function you want me to look at.

**Comment by archon810** [comment] 2016-09-16 16:39
Can we reopen this bug?

**Comment by dcramer** [comment] 2016-09-16 16:43
If I get some spare time I will try to turn the above example into a functional test case (though so far I seem to have been failing there).

**Comment by SeBsZ** [comment] 2016-09-18 23:06
So we seem to have found out that just changing the Sentry PHP SDK version breaks the suppression character's functionality.

We used to be on raven-php 0.14.0.dev0 and now we're on sentry-php 1.2.0. This upgrade actually caused suppressed errors to start showing up in the Sentry web console.

**Comment by dcramer** [comment] 2016-09-18 23:19
I'm intending to spend some time this week trying to turn the example into a usable test case, and once that's done I'm hoping it's fairly rival to weed out the bug.

**Comment by dcramer** [comment] 2016-09-19 16:45
Ah hah. I think I've been able to reproduce in PHP 5.6. It seems like this might not be an issue in 7 though.

**Comment by dcramer** [comment] 2016-09-19 16:57
Ok so the issue is that ``error_get_last`` seems to be NULL when we suppress it in this case. I dont believe that is *always* the case, so instead we're going to bind the "last error handled" to the value of ``error_get_last``, which will prevent this from showing up in the shutdown handler.

**Comment by dcramer** [comment] 2016-09-19 17:03
This is also making me question if we need the fatal error handler. I'd like to confirm if *all* errors are set to ``set_error_handler``, or if we'd miss some (like OOO). If the answer is yes, we're going to rm -rf it as it would greatly simplify code.

**Comment by SeBsZ** [comment] 2016-09-19 20:41
Thanks a lot dcramer. When do you think this fix would find its way into a stable release?

Would you like me to confirm the fix works for you?

**Comment by dcramer** [comment] 2016-09-19 20:48
@SeBsZ 1.3.0 includes this as well as a few other minor changes

**Comment by archon810** [comment] 2016-09-20 00:12
Thanks, all. I'll reopen if there are further issues.

**Comment by archon810** [comment] 2016-09-20 04:42
I have to request a reopen, unfortunately, @dcramer. Same issues still continuing to flow in, as far as I can tell, with SDK 1.3.0. 

Please see our apkmirror.com sentry page that I've linked you to before, you will see thousands of entries with @ suppressed code that started showing up after conversion to 1.2.0 and is still there with 1.3.0.

**Comment by dcramer** [comment] 2016-09-20 04:58
@SeBsZ can you confirm if your cases were even resolved? I'm a bit baffled that this is still happening.

@archon810 It's very possible its related to the same behavior I saw before, and the fix I put in place isn't enough. I would recommend killing the call to ``registerShutdownFunction``. I'm going to confirm if we actually need this, as it seems to be causing a lot of trouble. Also the fact that the stacktrace in your case is showing handleFatalError as the function seems odd. Correct me if I'm wrong, but that isn't the function name being called here?

**Comment by dcramer** [comment] 2016-09-20 05:04
Actually, just for more context, we currently try to bind the next frame as the current frame for various properties. This is clearly not working exactly as we want.

The reason we originally do this is because we try to make exceptions more contextually correct. When you are doing include_once() the function you're executing in is *not* include_once (though PHP gives us that function name in that frame).

**Comment by archon810** [comment] 2016-09-20 05:48
@dcramer @sebsz is actually my developer on apkmirror.com, so his results are my results, and what you see on the apkmirror.com sentry. I'll let him wake up and reply with his observations though.

**Comment by dcramer** [comment] 2016-09-20 06:12
It also sounds like fatal errors will never have a correct backtrace, though that may just be the internet mistaken.

**Comment by dcramer** [comment] 2016-09-20 06:20
@archon810 I've identified the core issue, and its purely our ignorance of PHP. The docs clearly state that certain classes of errors cant be passed to set_error_handler. Will get this fixed in #358.

**Comment by archon810** [comment] 2016-09-20 06:23
Did you confirm the regression that caused this to happen with 1.2 vs 0.14?

**Comment by dcramer** [comment] 2016-09-20 06:24
@archon810 yep, e2f077d72b7492b921752f3f4a7a27a3973469f3

**Comment by archon810** [comment] 2016-09-20 06:24
@sebsz can help test the new one.

**Comment by SeBsZ** [comment] 2016-09-20 14:57
@dcramer great! Your new branch overhaul-stacktraces definitely fixes the problem on my local dev machine. I had actually come up with a new test for you last night, then this morning I saw you had identified the issue yourself.

What I noticed last night was that if there was just a single suppressed error in my testfile, all was good. But if I added a real error/notice on the line above or below, it suddenly would start reporting even the suppressed error.

Anyway, that branch fixes the issue. I don't want to roll out modified files to production, so please let me know when you can get this into a **stable** release that we can roll out using composer.

Thanks again for your quick responses!

**Comment by dcramer** [comment] 2016-09-20 16:06
We'll get out a new version today with the changes.

**Closed by dcramer** 2016-09-20 16:06 UTC
