### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by m-ober** [getsentry/sentry-php#948] opened 2020-01-03 19:32 UTC
Composer warns:

> Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

See: https://www.zend.com/blog/what-status-zend-framework-transition-laminas

**Comment by ste93cry** [comment] 2020-01-03 19:37
This is the 4th issue about the same thing in a few days, we even pinned one at the top of the Issues page to make it standing out and let people know that it's already fixed in the upcoming release, thus I'm going to close this issue

**Closed by ste93cry** 2020-01-03 19:37 UTC

**Comment by Jean85** [comment] 2020-01-03 22:48
FTR, duplicate of #947
