### ISSUE TITLE
Parse error: syntax error, unexpected end of file in

### ISSUE THREAD

**Issue by hkaraoglu** [getsentry/sentry-php#1184] opened 2021-02-14 16:10 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP 3.1.4

### Steps to Reproduce

1. Sometimes php framework Codeigniter (4.0) app throws error like below
2. Parse error: syntax error, unexpected end of file in  /var/www/{appName}/public/index.php on line 76

### Expected Result

App should works.

### Actual Result

Parse error: syntax error, unexpected end of file in  /var/www/{appName}/public/index.php on line 76

<img width="762" alt="Screen Shot 2021-02-14 at 18 46 34" src="https://user-images.githubusercontent.com/7407515/107881373-231bcf00-6ef5-11eb-9cd4-900a87d722bd.png">

**My implementation:** 
public/index.php
```
  Sentry\init([
        'dsn' => getenv("SENTRY_DSN")
    ]);

```

**Comment by AndreKR** [comment] 2021-02-14 20:37
This has nothing to do with Sentry. Also, the error happens in line 76 but your index.php is just 3 lines long (and missing `<?php`), you probably pasted the wrong file.

**Comment by stayallive** [comment] 2021-02-14 20:57
@hkaraoglu I also think this is not because of Sentry but because an actual syntax error on line 76 or before it (possibly a forgotten `;` or closing brace somewhere).

Can you double check that?

**Comment by hkaraoglu** [comment] 2021-02-14 21:33
Guys there is no syntax error. It happens sometimes. If I add empty line into the end of the file, it is fixed strangely. I couldn't understand why it happens. Sometimes I restart the nginx server to fix it. It is not a producable error everytime.

**Comment by AndreKR** [comment] 2021-02-14 21:43
Do you have any opcode cache enabled? Those can cause such behavior. Anyway, quite certainly not related to Sentry.

**Comment by stayallive** [comment] 2021-02-15 09:28
Why did you come to Sentry to report this issue, is there something specific why you suspect Sentry is the culprit here?

I don't know what is happening but I concur I find it highly unlikely to be of fault to the Sentry SDK, the SDK is tested and used in many projects and this is the first I've heard of this specific issue being caused by Sentry, so far it's always an actual syntax error somewhere (not in Sentry) or caused by some process.

**Closed** 2021-02-15 09:29 UTC
Labels: Type: Question

**Comment by hkaraoglu** [comment] 2021-02-15 09:34
@stayallive I said It happens sometimes and I don't make any edition. And this problem started to happen after implemented sentry sdk. But maybe you are right. So I closed the issue.  In addition, I will consider @AndreKR 's opinion. Thanks
