### ISSUE TITLE
Errors are not send to sentry

### ISSUE THREAD

**Issue by maciejmackowiak** [getsentry/sentry-php#927] opened 2019-11-28 11:48 UTC
Hi,

We've got an issue with sentry/sdk:
errors are not send to sentry if a fatal error occurs during an output buffer callback or in other shutdown handler.

Step to reproduce:
1. Shutdown handler error:
```
//Register SENTRY
\Sentry\init(['dsn' => 'SENTRY_DSN']);
    \Sentry\configureScope(function (\Sentry\State\Scope $scope): void {
    $scope->setLevel(\Sentry\Severity::info());
});
register_shutdown_function(function(){
	not_a_function();
});
```
2. Output buffer callback error:
```
//Register SENTRY
\Sentry\init(['dsn' => 'SENTRY_DSN']);
    \Sentry\configureScope(function (\Sentry\State\Scope $scope): void {
    $scope->setLevel(\Sentry\Severity::info());
});
ob_start( function( $content ) {
	not_a_function();
	return $content;
} );
```
Both those examples will not be sent to sentry.
How can we account for those scenarios?

Here is our exact problem:
https://github.com/ampproject/amp-wp/issues/3825

**Comment by Jean85** [comment] 2019-11-28 14:33
Why are you setting the severity level in the `Scope`? Does it change anything?

**Comment by maciejmackowiak** [comment] 2019-11-28 14:38
Because Sentry docs says so:

> You can set the severity of an event to one of five values: fatal, error, warning, info, and debug. error is the default, fatal is the most severe and debug is the least severe.

https://docs.sentry.io/platforms/php/#setting-the-level

**Comment by Jean85** [comment] 2019-11-28 14:45
I meant: does removing that line from the example change the outcome? Is it necessary for the reproduction of the issue?

**Comment by maciejmackowiak** [comment] 2019-11-28 14:52
I've just tested it and removing that line doesn't change the outcome so it not necessary for the reproduction of the issue.

**Comment by Jean85** [comment] 2019-11-28 16:51
From what I see in https://github.com/ampproject/amp-wp/issues/3825, it seems something bound to how PHP works, so I fear that there's not much that we can do...

**Comment by cgsmith** [comment] 2019-12-12 18:30
I had an issue where errors were not sending with vanilla PHP similar to this... I didn't register a shutdown function. However, changing composer to use `sentry\sentry` instead of the SDK fixed it.

(i really dislike the sdk...)

**Comment by ste93cry** [comment] 2019-12-15 21:36
In both the cases mentioned in the first comment none of the error handlers (fatal or not) are called and so it's expected that the error is not logged by Sentry. However, triggering a standard error (e.g. with `trigger_error`) works and calls Sentry. Since this is how PHP works and there is nothing that we can do on our side anyway, I'm going to close this issue as "Won't fix"

**Closed by ste93cry** 2019-12-15 21:36 UTC
Labels: Status: Needs Information, Type: Bug

**Comment by archon810** [comment] 2019-12-15 22:10
@ste93cry @Jean85 @maciejmackowiak Any chance one of you will want to submit this as a bug to PHP?

**Comment by Jean85** [comment] 2019-12-16 08:41
It's not our issue, we do not have any stake in this, and I (at least) lack the expertise on this specific use case. You should do directly, since it seems something related on how that piece of software works.

**Comment by archon810** [comment] 2019-12-17 18:23
Found this open bug that is exactly what we need, so I'll add some more info there and we'll see if PHP devs address it: https://bugs.php.net/bug.php?id=78565.

Also this one seems related: https://bugs.php.net/bug.php?id=78495.
