### ISSUE TITLE
[2.0] Handle all types of callable

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#692] opened 2018-11-14 13:25 UTC
As reported in the review of #682, we have multiple points where we accept a callback (breadcrumbs, `before_send`...).

We need to test for all the kinds of `callable`, and use `call_user_func` to do it right.

**Comment by HazAT** [comment] 2018-11-16 13:53
I think we got all the spots now where this was necessary, right?
So we can close this.

**Comment by Jean85** [comment] 2018-11-16 15:45
In that case we would have 2 issues:
 * we have to add tests to be sure that no-one writes a regression in this respect
 * I'm not sure if that relying on the exception alone is a good practice: since this is an error reporting tool, blowing up with an exception while reporting an error is very bad! We should check that those cases  are stopped when setting the callable, not when using it!

**Comment by ste93cry** [comment] 2019-02-24 23:16
I'm going to close this as the issue is pretty old. Also adding tests for each type of `callable` for each place where we accept them would be so much work for no real benefit, since the typehint should be enough and if someone tries to pass something wrong then it's correct that an exception is thrown and if possible we will capture it anyway

**Closed by ste93cry** 2019-02-24 23:16 UTC
