### ISSUE TITLE
Sentry's Error Handler doesn't respect error types for the old error handler

### ISSUE THREAD

**Issue by Qcode** [getsentry/sentry-php#475] opened 2017-06-19 15:18 UTC
When you register Sentry with an old error handler already existing, it then sets the error types for its own handler to E_ALL. When that is called it checks to see if the error fits in the specified error types for its own handler (see lines 96-105 in ErrorHandler.php). However, if call_existing_error_handler is set to true, it doesn't do any check regarding error types, it just calls the old error handler assuming the user wants E_ALL.

Would it be possible to include a way to specify the error types for the old error handler? The project I'm trying to use this for already has an established error handler, but I don't want the old error handler to receive any E_STRICT errors.

**Comment by stayallive** [comment] 2017-06-20 22:18
This seems like a sane thing to do indeed.

After a quick search and debugging cannot find a way to get the old error handler type mask.

Having to supply the old error handler type mask seems silly, why not supply the error handler itself too if you are at it... hopefully there is a way to get the type mask for the current error handler.

Will have to dig a bit further to find an easy way to do this.

**Comment by ste93cry** [comment] 2018-05-13 22:47
As far as I know there is no way to get the error types that a previous error handler wants to receive and the issue is anyway quite old, so I'm going to close this.

**Closed by ste93cry** 2018-05-13 22:47 UTC
