### ISSUE TITLE
Issue with open_basedir restriction

### ISSUE THREAD

**Issue by Toflar** [getsentry/sentry-php#704] opened 2018-11-22 10:30 UTC
Hi everybody,

If during the session initialization there's an error, I do get the following warning in the stacktrace:

```

error_reporting | realpath(): open_basedir restriction in effect. File(/var/www/cgi-bin/cgi_wrapper) is not within the allowed path(s): (/var/www/:/tmp/)
-- | --
line | 96
code | 2
file | /var/www/vendor/sentry/sentry/lib/Raven/Stacktrace.php
```

So it seems like `Stacktrace` does not consider `open_basedir` when trying to report issues. It's strange I get a warning though because actually you use `@realpath()` which should suppress warnings. Anyway, maybe you know the issue there :)

**Comment by ste93cry** [comment] 2018-11-22 10:47
This is a duplicate of #653. We could not track down what's causing the issue, besides the fact that we don't purposefully read from outside the `open_basedir` path and that even if we check before if we can read that path an error is thrown and not suppressed. Do you have a reproducible test case or can you share some configuration and code that can help us with debugging?

**Comment by Jean85** [comment] 2018-11-22 12:11
Please share it in #653 if you're able. Closing this as duplicate.

**Closed by Jean85** 2018-11-22 12:11 UTC
