### ISSUE TITLE
Default `error_types` value

### ISSUE THREAD

**Issue by rcknr** [getsentry/sentry-php#841] opened 2019-06-26 09:51 UTC
The default value for `error_types` is set to `E_ALL` but not the effective `error_reporting` value. This is counter-intuitive and not mentioned in the [documentation](https://docs.sentry.io/error-reporting/configuration/?platform=php).

**Comment by Jean85** [comment] 2019-06-26 10:10
If you think that this is only a documentation issue, you can help yourself by submitting a PR to the docs repo. The page that you linked corresponds to this file: https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/error-reporting/configuration/index.md

**Comment by rcknr** [comment] 2019-06-26 11:14
I'm interested in the rationale behind this if there's one. 
I would set the default to `error_reporting()` return value and reflected this in the docs.

**Comment by ste93cry** [comment] 2019-06-26 12:31
I would say that the relationale behind this choice is that making the handler dependent on the `error_reporting` has both pros and cons. Specifically:

Pros:
- The handler respects the setting provided by the programming language to set which errors to report, regardless of where they should be reported

Cons:
- The user may want to report some errors to Sentry even though they are not reported on the screen or to the logging file. For example, I may want to not collect the deprecation errors in the logging file but I may still want to collect them to Sentry

These are just the two things that came to my mind while thinking about it, there may be more. Does it makes sense to you?

**Comment by rcknr** [comment] 2019-06-26 13:13
It doesn't make sense to me that `E_ALL` is the default value for this option. [PHP default](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) for it is different and it is not practical in the majority of use cases since it includes notice level errors. If somebody wants custom behavior as you mentioned in your contra-point they are free to do so by changing the default. With no setup, the expectation is to honor existing configuration. 
I've already submitted a [patch](https://github.com/getsentry/sentry-docs/pull/1080) to the docs so it is at least more visible. But ultimately I think it makes sense to change the default as well.

**Comment by Jean85** [comment] 2019-06-26 13:23
Changing the default value at this point would be a HUGE breaking change, because people would stop receiving events if they didn't set that value.

**Comment by rcknr** [comment] 2019-06-26 13:26
Agree it should be well planned but the option is not currently documented.

**Comment by Jean85** [comment] 2019-06-26 14:04
Yes, one of them is for the 1.x version of the SDK, which is older and it doesn't implement the Unified API.

**Comment by rcknr** [comment] 2019-06-26 15:11
I see that both documents describe SDK version 2. The later one mentions changes made in version 2 while the former gives codes examples specific to version 2.

**Comment by ste93cry** [comment] 2019-06-26 15:27
Here what's happening: there are indeed two pages describing almost the same things. The [first one](https://docs.sentry.io/error-reporting/configuration/?platform=php), which you linked in the first comment of this issue, is a page available globally for all SDKs (infact it's a generic `Configuration` page) and describes the options available in the Unified API since all SDKs adhering to the standard are supposed to share them and for this reason you can choose from the dropdown which language you want to see the options for, be it PHP or JS or whatever. The [second page](https://docs.sentry.io/platforms/php/) instead is specific of the PHP SDK and documents all the available options for that SDK only. Obviously, having them split between different pages is a total mess and things should be improved to be in one place only. Probably the best thing I would do is to have the `Configuration` page for each SDK and remove the global one, even though this will probably create some duplication it's more clear that everything relating to a specific SDK is in one place. The documentation for the `1.x` version of the SDK is under [another page](https://docs.sentry.io/clients/php/)

**Comment by rcknr** [comment] 2019-06-26 17:48
I propose to amend unified error tracking documentation right away. I've updated my [pull request](https://github.com/getsentry/sentry-docs/pull/1080) to indicate this option is only supported by PHP SDK.
If you agree that changing the default makes sense I'll prepare a pull request for that.

**Comment by ste93cry** [comment] 2019-06-26 20:59
>It doesn't make sense to me that `E_ALL` is the default value for this option. [PHP default](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) for it is different and it is not practical in the majority of use cases since it includes notice level errors. If somebody wants custom behavior as you mentioned in your contra-point they are free to do so by changing the default. With no setup, the expectation is to honor existing configuration.

If I understand correctly what you're saying, we can summarize it with the expected behavior that Sentry should capture by default the same errors that would be reported according to the `error_reporting` option because reporting (just an example) notice level errors is something you don't want to happen. I may agree in some form with this, but I don't have a strong opinion on this. Said this and clarified that we cannot change the default without breaking the behavior for existing users, I have another proposal: let's add another flag option that enables reporting only the errors which severity match with the `error_reporting` option. Following this, there will be 3 cases by which an error is reported to Sentry:

- If `capture_error_reporting_errors_only = true` (name to define yet) and the severity doesn't match with the `error_reporting` bitmask don't report it
- If `capture_error_reporting_errors_only = false` (this wil be the default to not break BC) and the severity doesn't match with the `error_types` option don't report it

It remains unknown at which point the `capture_silenced_errors` should act, probably after the two checks above. This  solution won't solve the problem immediately as you will still have to turn it on manually, but it can be turned on by default on the next major version. This way users can choose if they want to be dependent on the `error_reporting` option to capture errors or not. Does it makes more sense to you?

**Comment by rcknr** [comment] 2019-06-26 22:29
No, it doesn't. Adding another option brings more confusion regarding what will be reported.
As of right now, it is clear what `capture_silenced_errors` does. It is documented and reflects a real use case.
I see the following problems with the current default value:

- It doesn't match the language's default value
- It doesn't honor existing configuration
- Can produce too many events which is neither desirable by users nor by Sentry
- Is not described in the documentation.

Regarding the last point, we've found there are a few versions of documentation but the one linked from the project's README doesn't have it mentioned. It is also not mentioned in the UPGRADE docs!

I've found the commit where the default was first set (it is from you) and I see that it was done to set the type of this option to integer.

Changing the default to the return value of `error_reporting` will reflect existing error reporting preference whether language default or customized, as well as allow to control this preference from a single point (e. g. php.ini) while still enabling customization specific to Sentry.

**Comment by ste93cry** [comment] 2019-06-27 08:14
Got it, unfortunately as we already said we cannot change the default or we it would be a BC. I'm sorry, the only thing that we can actually do like you did is update the both the documentation and the `UPGRADE.md` file

**Comment by rcknr** [comment] 2019-06-27 09:07
I understand that you can't change it right away, however, you can change it in the next version (2.2). So should I prepare a PR then?

**Comment by ste93cry** [comment] 2019-06-27 09:11
We cannot even in the next minor version, a BC can happen only between major version bumps. Even if it's true that we don't write anywhere that we strictly follow Semver, we strive to do it implicitly and I don't want to change this :wink:

**Comment by rcknr** [comment] 2019-06-27 09:14
This is not a breaking change though. This change won't break error reporting.
This is a bug fix as it prevents potential flooding with notice-level messages.

**Comment by ste93cry** [comment] 2019-06-27 09:19
This is a BC because it changes the behavior of an existing feature for users who update and who suddenly stop receiving errors if they have not explicitly configured the option

**Comment by rcknr** [comment] 2019-06-27 09:35
Breaking change is a change that potentially can lead to a system's failure.
Let's look at the situation from the perspective of a user upgrading from version 1.
The previous default was equal to `error_reporing` ([see here](https://github.com/getsentry/sentry-php/blob/1.10.0/lib/Raven/ErrorHandler.php#L111)). Suddenly, after upgrading (having read your upgrade docs and keeping the same configuration) you are getting a flood of notices which can potentially bring an otherwise working system down, deplete subscription limits and overload reporting servers.
Yes, changing the default will make some events disappear but not all of them and it will certainly not gonna lead to a failure to capture errors completely.
What do you see as a possible scenario where this leads to a system's failure?

**Comment by Jean85** [comment] 2019-06-27 11:23
> Breaking change is a change that potentially can lead to a system's failure.

No it's not. We're talking about BC in a Semantic Versioning context. You can read about it here: https://semver.org/

**Comment by ste93cry** [comment] 2019-06-27 11:39
To clarify, this is not a technical BC but a behavior breaking change. Suppose that I'm a user that upgraded from version `1.x` to `2.x`, and although in the `UPGRADE.md` file it was not mentioned (this is one issue of course and we have to fix it) the behavior of the library changed causing the error handler to not respect the `error_reporting` option by default. This is undocumented, but it's still a valid change as there was a major version bump. I also decided for some reason that the default is good for me. Now, what you are saying is that in `2.2` you want to change again the behavior causing pain for the users because suddenly they stop receiving errors, and the point is not how many errors they will lose but the fact that an upgrade between patch and minor versions should not require any change to the configuration to make existing features work as before. This is because users pinning to e.g. `^2.0` will get the new minor versions but not the new major versions, so they won't even notice that something is not working anymore as expected. We are more than welcome to improve the documentation and change the default for `3.0`, but not before that version

**Comment by ste93cry** [comment] 2019-07-09 07:51
FYI: #846 changes the parameter typehint as discussed in this issue. Closing this for now, changing the default value for the option will be discussed (and likely done) when the time for `3.0` comes

**Comment by ste93cry** [comment] 2019-07-09 07:52
Closing this for now, changing the default value for the option will be discussed (and likely done) when the time for `3.0` comes

**Closed by ste93cry** 2019-07-09 07:51 UTC
Labels: Status: Confirmed, Type: Documentation
