### ISSUE TITLE
Could not encode value into JSON format. Error was: \"Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by 4n70w4** [getsentry/sentry-php#828] opened 2019-06-06 10:59 UTC
```
{
"message": "Could not encode value into JSON format. Error was: \"Malformed UTF-8 characters, possibly incorrectly encoded\".",
"exception": "Sentry\\Exception\\JsonException",
"file": "/var/www/app/vendor/sentry/sentry/src/Util/JSON.php",
"line": 30,
"trace": [
{
"file": "/var/www/app/vendor/sentry/sentry/src/Transport/HttpTransport.php",
"line": 78,
"function": "encode",
"class": "Sentry\\Util\\JSON",
"type": "::"
},
{
"file": "/var/www/app/vendor/sentry/sentry/src/Client.php",
"line": 105,
"function": "send",
"class": "Sentry\\Transport\\HttpTransport",
"type": "->"
},
{
"file": "/var/www/app/vendor/sentry/sentry/src/Client.php",
"line": 96,
"function": "captureEvent",
"class": "Sentry\\Client",
"type": "->"
},
```

**Comment by Jean85** [comment] 2019-06-06 11:26
Can you provide us the payload that generated this error? Do you have any other indication to where this issue may have originated?

**Comment by 4n70w4** [comment] 2019-06-06 12:45
@Jean85 not now, but I set a trap in production to collect detailed information if such an error occurs again.

**Comment by kocoten1992** [comment] 2019-06-09 16:59
might related this one, https://github.com/getsentry/sentry-laravel/issues/236

**Comment by Jean85** [comment] 2019-06-10 07:21
If we have binary data here too, yeah...

**Comment by 4cc355-d3n13d** [comment] 2019-07-06 01:07
+1, very annoying

**Comment by 4cc355-d3n13d** [comment] 2019-07-06 01:17
@Jean85 catching payload for this error is not the easy thing. Possible multibyte chars (emojies and arabic chars) causing this error

**Comment by 4n70w4** [comment] 2019-07-09 09:15
Example exception message:

`Command "жопж78yuihjkТ is not defined.`

May be symbols filtered by github.

Example exception message as base64:

```
Q29tbWFuZCAi0LbQvtC/0DY3OHl1aWhqa7AiIGlzIG5vdCBkZWZpbmVkLg
```

Example exception message as hex:

```
436F6D6D616E642022D0B6D0BED0BFD0
363738797569686A6BB022206973206E
6F7420646566696E65642E
```

**Comment by ejunker** [comment] 2019-07-12 21:00
I am using the laravel-sentry integration and I ran into this issue because I have a database table with a column of type `VARBINARY` and the `sql.query` breadcrumbs ocassionaly contained binary strings that caused the `json_encode()` to fail. I was able to update my queries so that instead of inserting binary data directly, I ran in through MySQL's `HEX()` function to convert it to a hex string which then prevented the UTF-8 error.

I think this is an example of a simple way to reproduce this error:
```php
        addBreadcrumb(new Breadcrumb(
            Breadcrumb::LEVEL_ERROR,
            Breadcrumb::TYPE_ERROR,
            'error_reporting',
            pack('H*', md5('binary string'))
        ));

        throw new \Exception('testing sentry');
```

I think the only possible options are to ignore the JSON UTF-8 errors or else to convert all the strings to UTF-8.

If you want to ignore the errors, with PHP >= 7.2 you could add `JSON_INVALID_UTF8_IGNORE` to `Sentry\Util\JSON` so that it looks like:
```php
$encodedData = json_encode($data, JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_IGNORE);
```

I did not have these errors until I upgraded from version 1.9 to 2.0 of `sentry/sentry-php`. It looks like in the old Raven client that it had code like `mb_convert_encoding($value, 'UTF-8');` which handles converting everything to UTF-8 and didn't have this issue with binary data. I don't think Sentry can predict what type of data will be sent to it. Maybe the new version needs to convert all strings to UTF-8 to prevent this issue.

**Comment by pdbreen** [comment] 2019-07-16 17:50
As others have indicated, the primary issue is failure to encode json if accumulated event data contains binary (just surfaced for us).  There's a secondary issue here as well -- the Json exception being thrown is escaping the Sentry API boundary (`captureEvent`).  Failure to capture an event should not create a new unexpected (and undocumented) exception condition.

**Comment by Jean85** [comment] 2019-07-18 11:21
> If you want to ignore the errors, with PHP >= 7.2 you could add JSON_INVALID_UTF8_IGNORE to Sentry\Util\JSON ...

We could do that and leverage the Symfony PHP 7.2 polyfill. @ste93cry WDYT?

**Comment by ste93cry** [comment] 2019-07-18 11:47
I would like to use `JSON_INVALID_UTF8_SUBSTITUTE` which seems to better fit this since it would replace the invalid UTF-8 character with the standard replacement char, however the polyfill cannot replace existing core functions so it won't work. We should solve the issue on our side, probably not everything is running through the serializer and converted to UTF-8

**Comment by alexchuin** [comment] 2019-07-22 14:45
We have the same problem here since yesterday...

`Uncaught Exception: Could not encode value into JSON format. Error was: "Malformed UTF-8 characters, possibly incorrectly encoded". {"exception":"[object] (Sentry\\Exception\\JsonException(code: 0): Could not encode value into JSON format. Error was: "Malformed UTF-8 characters, possibly incorrectly encoded".`

**Comment by kocoten1992** [comment] 2019-08-20 15:15
Any chance we could push this ?

I (have to) temporary remove sentry package, since it doesn't report Exception due to this error

**Comment by ferranfg** [comment] 2019-08-20 15:31
Our temporary "fix" is ignoring the errors regarding this issue, so we have something like:

```php
/**
 * Report or log an exception.
 *
 * @param  \Exception  $exception
 * @return void
 */
public function report(Exception $exception)
{
    if ( ! app()->isLocal() && app()->bound('sentry') && $this->shouldReport($exception))
    {
        try
        {
            app('sentry')->captureException($exception);
        }
        catch (Exception $e)
        {
            // https://github.com/getsentry/sentry-php/issues/828
        }
    }

    parent::report($exception);
}
```

I know how ironic it is and we are missing some errors with Sentry, but still it's the only solution we have found.

**Comment by jun3453** [comment] 2019-08-24 11:25
I had the same problem.
When I examined it in detail, it was an error because I used MsgPack.
https://github.com/getsentry/sentry-php/issues/828#issuecomment-512802064
I was able to send it by doing the following.

```
    Sentry\init([
        'dsn' => $dsn,
        'before_send' => function (Sentry\Event $event): ?\Sentry\Event {
            $event->setRequest([]);
            return $event;
        },
    ]);
```

I think you can do the same with other binary formats.

**Comment by Jean85** [comment] 2019-08-30 14:29
Unfortunately we cannot use `JSON_INVALID_UTF8_IGNORE` with `json_encode` since it requires PHP 7.1. Maybe we should recursively pass all strings through `iconv('UTF-8', 'UTF-8//IGNORE', $s)`, but I'm not sure if we have a centralized place in the code to cover all cases.

**Comment by 4cc355-d3n13d** [comment] 2019-09-19 21:18
Maybe user JSON encoder (possibility of giving already encoded Sentry Event) as a simple workaround? 🙏

**Comment by Jean85** [comment] 2019-09-20 07:10
That's already possible, you can set the serializer in the `ClientBuilder`

**Comment by rafaeltovar** [comment] 2019-10-24 09:58
+1

**Comment by jamesgraham** [comment] 2019-10-25 16:34
What can be done to resolve this? I am in favour of the 7.2 workaround, for those of us using modern PHP it at least removes an awful hack...

**Comment by rafaeltovar** [comment] 2019-10-25 16:53
> What can be done to resolve this? I am in favour of the 7.2 workaround, for those of us using modern PHP it at least removes an awful hack...

Maybe something like?

```php
// Sentry\Util\JSON.php
...
public static function encode($data): string
{

  if(version_compare (PHP_VERSION , "7.2" , ">=")
    $encodedData = json_encode($data, JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_IGNORE);
  else {
    // another $data parser or no
    $encodedData = json_encode($data, JSON_UNESCAPED_UNICODE);
  }

  if (JSON_ERROR_NONE !== json_last_error() || false === $encodedData) {
    throw new JsonException(sprintf('Could not encode value into JSON format. Error was: "%s".', json_last_error_msg()));
  }
  
  return $encodedData;
}
```

**Comment by voodoo-dn** [comment] 2019-11-01 11:46
My solution while not fixed in repository:

composer.json
`"autoload": {
        "exclude-from-classmap": ["vendor/sentry/sentry/src/Util/JSON.php"],
        "psr-4": {
            "App\\": "src/",
            "Sentry\\Util\\": "src/Infrastructure/Sentry/Util/"
        }
    }`

Copied \Sentry\Util\JSON to rc/Infrastructure/Sentry/Util/ folder, added JSON_INVALID_UTF8_IGNORE in json_encode function.

**Comment by jaylinski** [comment] 2019-11-06 16:38
> Unfortunately we cannot use `JSON_INVALID_UTF8_IGNORE` with `json_encode` since it requires PHP 7.1. Maybe we should recursively pass all strings through `iconv('UTF-8', 'UTF-8//IGNORE', $s)`, but I'm not sure if we have a centralized place in the code to cover all cases.

The option `JSON_INVALID_UTF8_IGNORE` requires PHP 7.2 (if anyone wondered why it wasn't used)

https://www.php.net/manual/en/function.json-encode.php

**Comment by jamesgraham** [comment] 2019-11-07 01:01
> > Unfortunately we cannot use `JSON_INVALID_UTF8_IGNORE` with `json_encode` since it requires PHP 7.1. Maybe we should recursively pass all strings through `iconv('UTF-8', 'UTF-8//IGNORE', $s)`, but I'm not sure if we have a centralized place in the code to cover all cases.
> 
> The option `JSON_INVALID_UTF8_IGNORE` requires PHP 7.2 (if anyone wondered why it wasn't used)
> 
> https://www.php.net/manual/en/function.json-encode.php

That's true but PHP 7.2 has been stable for a year. For teams using this version can the SDK not provide some relief? What is the rationale behind not supporting recent versions?

**Comment by Jean85** [comment] 2019-11-07 10:56
The issue is not in "supporting recent versions", whether to require it, cutting out users still using 7.1.

I'll try to dive a bit onto this issue now, to see if I can draft a possible fix.

**Comment by ste93cry** [comment] 2019-11-07 11:16
I would add my two cents on the discussion: I'm more than happy to use `JSON_INVALID_UTF8_IGNORE` wrapped around a `version_compare` check, however this is not a fix for all users (what about people using older PHP versions that we still support?) so I don't think we should go this way. Instead, we should patch the serializer (and honestly I would rewrite it from scratch if I had the time to do it as its code is one of the worst I've ever seen)

**Comment by Jean85** [comment] 2019-11-07 17:42
I've attempted a fix with #920. @4n70w4 @4cc355-d3n13d @ejunker @pdbreen @alexchuin @kocoten1992 @ferranfg @jun3453 @rafaeltovar @jamesgraham @voodoo-dn @jaylinski can you please test it out to see if that resolves your issue?

The fix is not perfect due to not wanting to break BC; in the next major version I would prefer to require at least PHP 7.2 and use `JSON_INVALID_UTF8_SUBSTITUTE`, and move the serializer completely in the flow, making it the last step before passing data to the transport, so we can be sure that we would catch anything.

**Comment by TheLevti** [comment] 2019-11-09 12:21
Php version 7.1 runs out of support on the 1st of Dec 2019 anyway.

Got the same issue on my projects.

**Comment by Jean85** [comment] 2019-11-11 08:41
The fix doesn't seem to work, due to the fact that our serializer isn't able to serialize whole objects :disappointed:

**Comment by ste93cry** [comment] 2019-12-15 17:49
>Php version 7.1 runs out of support on the 1st of Dec 2019 anyway.

Indeed, and I would really like to drop support for it but it's not feasible because of a lot of people still using it. Anyway, I opened a new PR that attempts to fix the issue for all PHP versions that we support. Since I'm touching how we serialize events the code is pretty critical and I hope to not have broke something, so any person willing to test it and report back if it works of it there are problems is more than welcome!

**Closed** 2019-12-17 17:42 UTC
Labels: Status: Confirmed, Type: Bug

**Comment by KaviiChathuranga** [comment] 2020-08-13 04:40
> I am using the laravel-sentry integration and I ran into this issue because I have a database table with a column of type `VARBINARY` and the `sql.query` breadcrumbs ocassionaly contained binary strings that caused the `json_encode()` to fail. I was able to update my queries so that instead of inserting binary data directly, I ran in through MySQL's `HEX()` function to convert it to a hex string which then prevented the UTF-8 error.
> 
> I think this is an example of a simple way to reproduce this error:
> 
> ```
>         addBreadcrumb(new Breadcrumb(
>             Breadcrumb::LEVEL_ERROR,
>             Breadcrumb::TYPE_ERROR,
>             'error_reporting',
>             pack('H*', md5('binary string'))
>         ));
> 
>         throw new \Exception('testing sentry');
> ```
> 
> I think the only possible options are to ignore the JSON UTF-8 errors or else to convert all the strings to UTF-8.
> 
> If you want to ignore the errors, with PHP >= 7.2 you could add `JSON_INVALID_UTF8_IGNORE` to `Sentry\Util\JSON` so that it looks like:
> 
> ```
> $encodedData = json_encode($data, JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_IGNORE);
> ```
> 
> I did not have these errors until I upgraded from version 1.9 to 2.0 of `sentry/sentry-php`. It looks like in the old Raven client that it had code like `mb_convert_encoding($value, 'UTF-8');` [Raven Serializer](https://github.com/getsentry/sentry-php/blob/1.9.2/lib/Raven/Serializer.php#L102) handles converting everything to UTF-8 and didn't have this issue with binary data. I don't think Sentry can predict what type of data will be sent to it. Maybe the new version needs to convert all strings to UTF-8 to prevent this issue.

wow. this can fix that Error 

      if ($data instanceof Jsonable) {
            $this->data = $data->toJson($this->encodingOptions);
        } elseif ($data instanceof JsonSerializable) {
            $this->data = json_encode($data->jsonSerialize(), $this->encodingOptions);
        } elseif ($data instanceof Arrayable) {
            $this->data = json_encode($data->toArray(), $this->encodingOptions);
        } else {
//            $this->data = json_encode($data, $this->encodingOptions);
            $this->data = json_encode($data, JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_IGNORE);
        }

        if (!$this->hasValidJson(json_last_error())) {
            throw new InvalidArgumentException(json_last_error_msg());
        }
