### ISSUE TITLE
Bug in error handler?

### ISSUE THREAD

**Issue by thomasvargiu** [getsentry/sentry-php#973] opened 2020-02-07 18:27 UTC
I don't know why in these lines of code the error handler throws the exception again.

This is causing the exception to be converted in an `E_ERROR`, then catched again by the shutdown function. This behaviour causes the error to be logger twice, triggering other shutdown functions, and logging it (the `E_ERROR`) with a stack trace (because when converted, the message contains the stack trace) with possible secrets in parameters (it's logging my database secrets when my app fails to connect).

https://github.com/getsentry/sentry-php/blob/a74999536b9119257cb1a4b1aa038e4a08439f67/src/ErrorHandler.php#L444-L452

The previous handler is already called, I think we should just `return`, but maybe I'm not thinking to other behaviours.

**Comment by ste93cry** [comment] 2020-02-07 21:22
Can you please provide a simple test case that reproduces the issue? Being the first time I see this it would help a lot to understand what's going on

**Comment by thomasvargiu** [comment] 2020-02-10 13:55
Hi, IMHO the problem is that even if the exception is handled, it is always thrown.
The exception handler is to handle an exception, so it's not necessary to throw it again.
I saw that the code is very similar to the symfony error handler, but it throws an exception only when there is another exception while handling it:

https://github.com/symfony/error-handler/blob/33ea3274749b635b6af9a5dbb2cdf53dabc55536/ErrorHandler.php#L597-L603

So I think the following assertion is wrong:

https://github.com/getsentry/sentry-php/blob/7acdcdd1d507e29a38b4c282527a2ae3c9fca130/tests/phpt/error_handler_captures_exception.phpt#L44-L46

**Comment by ste93cry** [comment] 2020-02-10 14:16
>even if the exception is handled, it is always thrown

This was meant to be that way because the error handler of Sentry is not meant to catch exceptions and hide them but just to log them. If you want to catch exceptions and e.g. render an error page then it's up to you to set another exception handler. However having that `return` statement probably makes definitely sense and I would gladly accept a contribution to fix it, but before doing it having a small example that reproduces the issue and what you expect would make things a lot easier if we have to reason about it

>I saw that the code is very similar to the symfony error handler

It is because in effect the code is largely based on that component

**Comment by ste93cry** [comment] 2020-02-10 14:17
>Hi, IMHO the problem is that even if the exception is handled, it is always thrown.
>The exception handler is to handle an exception, so it's not necessary to throw it again.

Having that `return` statement probably makes definitely sense and I would gladly accept a contribution to fix it, but before doing it having a small example that reproduces the issue and what you expect would make things a lot easier if we have to reason about it

>I saw that the code is very similar to the symfony error handler

It is because in effect the code is largely based on that component

**Comment by Jean85** [comment] 2020-02-10 14:52
I discussed with @thomasvargiu in person the issue, he convinced me and we've found a small reproduction case.

The assumption is: **if I enable Sentry, the behavior of my application shouldn't change**, right?
That isn't true if we do not add a `return` in our error handler.

To reproduce this case you just have to act on this PHP test: https://github.com/getsentry/sentry-php/blob/2.3.1/tests/phpt/error_handler_captures_exception.phpt

If you comment out all the Sentry-related code, the output changes in this way:
```diff
-Exception listener called
Custom exception handler called
-Fatal error: Uncaught Exception: foo bar in %s:%d
-Stack trace:
-#0 {main}
-  thrown in Standard input code on line 36
```
The first line is expected to disappear, it's part of the test. But the native raising of the error to a fatal as an Uncaught Exception is no longer present. This means that if the end user has an exception handler to avoid raising any exception for any reason, it will not work anymore with Sentry because it will always re-throw the error and make it reach the status of Uncaught Exception.

**Comment by ste93cry** [comment] 2020-02-10 14:57
Got it, it is definitely a bug: contribution to fix the issue is more than welcome!

**Comment by ste93cry** [comment] 2020-02-16 14:10
>The exception handler is to handle an exception, so it's not necessary to throw it again.

I thought again about why I coded the handler to always throw and I avoided that `return` statement, and the reason is that we're a logging library, so it's not the purpose of our handler to hide under the hood a certain exception which is what is happening if we do this change. While it's true that if the user sets an handler using `set_exception_handler` and that handler does not rethrow the exception then the exception itself gets suppressed, this is a choice he made knowingly. The current behavior of our handler respects perfectly what would happen if no handler was registered ever, and is what happens even with the Symfony error handler if you disable the custom printing of the exception with the following code:

`\Symfony\Component\ErrorHandler\ErrorHandler::register()->setExceptionHandler(null);`

>This is causing the exception to be converted in an `E_ERROR`, then catched again by the shutdown function. This behaviour causes the error to be logger twice

If the exception being rethrown is the same we're handling then our fatal error handler gets disabled, thus it should not be logged twice 🤔

**Comment by ste93cry** [comment] 2020-03-09 13:45
Closing because the fix has been released

**Closed by ste93cry** 2020-03-09 13:45 UTC
Labels: Status: Confirmed, Type: Bug
